### ISSUE TITLE
Does it supports multiple Compose files?

### ISSUE THREAD

**Issue by osya** [p1c2u/vscode-docker-compose#10]
Support for multiple Compose files still in progress for PyCharm (https://youtrack.jetbrains.com/issue/IDEA-159935). Does this extension supports it?

**Comment by p1c2u** [comment]
@osya yes, you can define it with `docker-compose.files`setting. By default it's ["docker-compose.yml"]

**Comment by osya** [comment]
@p1c2u , Thanks

**Comment by dntq83** [comment]
Can you show me? How can i setting  docker-compose.files?

Thank you
