### ISSUE TITLE
Unable to use this extension on VS Code on Windows 10

### ISSUE THREAD

**Issue by qnm** [p1c2u/vscode-docker-compose#14]
This looks like a great extension - however running it on Windows 10 results in the error: `Failed to retrieve project containers`. I'm assuming this is because the extension assumes a POSIX environment.

I had a quick look through the https://github.com/Microsoft/vscode-docker repo and it looks like the solution could be as simple as replacing `/bin/sh` with `powershell` - see the code reference here: https://github.com/Microsoft/vscode-docker/blob/master/commands/open-shell-container.ts#L11

If I get the time I'll put together a PR, but if I'm missing a configuration option - please let me know!

**Comment by p1c2u** [comment]
@qnm hi, thanks for the report. Attached shell command is used inside container. You should try to change `docker-compose.shell` setting
