### ISSUE TITLE
Docker-Compose Extension Error: Unexpected end of JSON input

### ISSUE THREAD

**Issue by AlekseiGrigorev** [p1c2u/vscode-docker-compose#55]
Error on click on extension icon - Docker-Compose Extension Error: Unexpected end of JSON input

**Comment by p1c2u** [comment]
what docker and docker compose versions do you have installed?

**Comment by AlekseiGrigorev** [comment]
I use  Docker Desktop 4.23.0 (120376), Docker Engine v24.0.6 build
ed223bc, Docker Compose version v2.21.0-desktop.1
OS Windows 11 22H2 build 22621.2283

VS Code
Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by p1c2u** [comment]
@AlekseiGrigorev  It seems to be related to Docker Desktop for Windows issue

Check https://github.com/docker/for-win/issues/13180 and https://github.com/docker/desktop-linux/issues/57

**Comment by AlekseiGrigorev** [comment]
Yes, it looks like it. Thank you!
